### ISSUE TITLE
PJLink not accepting password to PT-EW650U Projector

### ISSUE THREAD

**Issue by logancof** [bitfocus/companion-module-pjlink#4]
We have tried changing every password on the projector to make it work. We used the default password (panasonic) and even created a service password. Our companion connects to the projectors ip, but when we hit a button, it says the password is incorrect. 

instance(pjlink): Authentication error. Password not accepted by projector

**Comment by dali01** [comment]
We're experiencing the same issue with another Panasonic model.
Is anyone looking at these issues?

**Comment by haakonnessjoen** [comment]
If someone else than me could look at the API spec and the code for password with fresh eyes, that would help a lot. I am blinded by my own code, as I cannot see reason it does not work.

**Comment by istnv** [comment]
I looked into this. I think the API spec has a typo. 
The digest example states that `498e4a67 JBMIAProjectorLink` should generate `5d8409bc1c3fa39749434aa3a5c38682` but it doesn't.
Remove the space between: `498e4a67JBMIAProjectorLink` then it does result in `5d8409bc1c3fa39749434aa3a5c38682`

**Comment by dali01** [comment]
@istnv is definitely on to something here.
And the API spec says:

> The password string “JBMIAProjectorLink” is added to the end of the random sequence “498e4a67” issued by .the Projector/Display

It doesn't say that it should be added with a space. So there is for sure a typo in the next sentence:

> The digest of the resultant string “498e4a67 JBMIAProjectorLink” is carried out with the MD5 algorithm.

**Comment by haakonnessjoen** [comment]
Great research guys! I hate when specs are wrong on so important stuff. If anyone could test the latest 2.0 build now, that would be awesome! I still have a possible update if the projector is not responding for a second command within a second.

**Comment by dali01** [comment]
I will test it tonight.

**Comment by istnv** [comment]
I looked into this because I'm adding companion control to a few things in the theater, one being the projector that is upstairs from my primary position. I finally got the chance to wire it up and the new build works on a NP-PX750U with the password set.

**Comment by haakonnessjoen** [comment]
Closing this as this seems to have been the issue all along, and it should be working for everyone now.

**Comment by dali01** [comment]
@haakonnessjoen  I've now tested it on my Panasonic PT-VZ580, and unfortunately the issue remains.
Since companion doesn't output much debugging info, it's hard to see what happens.
I've tested with a generic pjlink client, and that works fine with my projector.
I did try to uninstall companion before installing the latest version, to make sure that I have the latest version of the pjlink plugin.

**Comment by istnv** [comment]
This page has PJLink specifications and testing utilities:
[https://pjlink.jbmia.or.jp/english/dl_class2.html](url)

**Comment by dali01** [comment]
@haakonnessjoen When can Dan's fix be merged in to 2.0 beta?
